### ISSUE TITLE
Use derived without Dispatchers.Main

### ISSUE THREAD

**Issue by amir1376** [ensody/ReactiveState-Kotlin#30]
I have a simple console application that I want to use 'derived' to map some  state flows
can I do that without `Dispatchers.Main` ?
I can't figure out why `derived` needs the Main Dispatcher . (why not using `Dispatchers.Default` ? by default)

**Comment by amir1376** [comment]
where can I pass dispatcher ?
I read the library and some of its functions accept a `coroutineScope` as their receivers 

here is my sample code 

```kotlin
import com.ensody.reactivestate.*
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.update

val appScope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

val number = MutableStateFlow(5)
val isPrime = appScope.derived {
    get(number) % 2 == 0
}

fun main() = runBlocking<Unit> {
    launch {
        while (isActive) {
            number.update { it + 1 }
            delay(1000)
        }
    }
    //we are in coroutineScope
    autoRun {
        println("${get(number)} is  ${get(isPrime)}")
    }
}
```
when I run this code I get this this error btw
```
5 is  false
Exception in thread "main" java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
	at kotlinx.coroutines.internal.MainDispatchersKt.throwMissingMainDispatcherException(MainDispatchers.kt:81)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:112)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:96)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:319)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.ensody.reactivestate.SharedCollect.collect(OnDemandStateFlow.kt:98)
	at com.ensody.reactivestate.DefaultOnDemandStateFlow.collect(OnDemandStateFlow.kt:167)
	at com.ensody.reactivestate.StateFlowObservable$addObserver$1.invokeSuspend(AutoRunStateFlow.kt:26)
	at com.ensody.reactivestate.StateFlowObservable$addObserver$1.invoke(AutoRunStateFlow.kt)
	at com.ensody.reactivestate.StateFlowObservable$addObserver$1.invoke(AutoRunStateFlow.kt)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1$1.invokeSuspend(CoroutineLauncher.kt:61)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1$1.invoke(CoroutineLauncher.kt)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1$1.invoke(CoroutineLauncher.kt)
	at com.ensody.reactivestate.CoroutineLauncher$DefaultImpls.track(CoroutineLauncher.kt:83)
	at com.ensody.reactivestate.SimpleCoroutineLauncher.track(SimpleCoroutineLauncher.kt:10)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1.invokeSuspend(CoroutineLauncher.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at MainKt.main(Main.kt:13)
	at MainKt.main(Main.kt)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@309e345f, Dispatchers.Main[missing]]
Exception in thread "main" java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
	at kotlinx.coroutines.internal.MainDispatchersKt.throwMissingMainDispatcherException(MainDispatchers.kt:81)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:112)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:96)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:319)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.ensody.reactivestate.SharedCollect.collect(OnDemandStateFlow.kt:98)
	at com.ensody.reactivestate.DefaultOnDemandStateFlow.collect(OnDemandStateFlow.kt:167)
	at com.ensody.reactivestate.StateFlowObservable$addObserver$1.invokeSuspend(AutoRunStateFlow.kt:26)
	at com.ensody.reactivestate.StateFlowObservable$addObserver$1.invoke(AutoRunStateFlow.kt)
	at com.ensody.reactivestate.StateFlowObservable$addObserver$1.invoke(AutoRunStateFlow.kt)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1$1.invokeSuspend(CoroutineLauncher.kt:61)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1$1.invoke(CoroutineLauncher.kt)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1$1.invoke(CoroutineLauncher.kt)
	at com.ensody.reactivestate.CoroutineLauncher$DefaultImpls.track(CoroutineLauncher.kt:83)
	at com.ensody.reactivestate.SimpleCoroutineLauncher.track(SimpleCoroutineLauncher.kt:10)
	at com.ensody.reactivestate.CoroutineLauncher$launch$1.invokeSuspend(CoroutineLauncher.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at MainKt.main(Main.kt:13)
	at MainKt.main(Main.kt)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@309e345f, Dispatchers.Main[missing]]
```

**Comment by wkornewald** [comment]
There are two different kinds of derived: blocking and suspend based. Passing a dispatcher only makes sense for suspend based code. There you can use `derived(initialValue, dispatcher = dispatchers.default)`. The CoroutineScope isn't absolutely necessary and it has nothing to do with the dispatcher.

However, you're trying to run this code on a target that doesn't have a main dispatcher at all. This lib currently requires one, though, and a fix would be needed to make it work at all.

**Comment by amir1376** [comment]
Thanks
That's right I was thinking that maybe you are using the scope's dispatcher.I didn't know that there is another overload that accept dispatcher

BTW, it will be good to support environments with no dispatchers to set Dispatchers.Default as a fallback
